include: package:very_good_analysis/analysis_options.yaml

linter:

  rules:
    public_member_api_docs: false
    use_build_context_synchronously: false
    use_colored_box: false
    use_decorated_box: false
    one_member_abstracts: false
    avoid_bool_literals_in_conditional_expressions: false
    avoid_positional_boolean_parameters: false
    no_default_cases: false
    avoid_redundant_argument_values: false
    lines_longer_than_80_chars: false

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "/pubspec.yaml"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.gen.dart"
  language:
    strict-casts: true
    strict-raw-types: true

