name: movie_app
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/very_good_analysis
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true



