name: movie_app
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flutter_dotenv: ^5.1.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  provider: ^6.1.1
  equatable: ^2.0.5
  connectivity_plus: ^5.0.2
  flutter_screenutil: ^5.9.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1

  # https://pub.dev/packages/very_good_analysis
  very_good_analysis: ^5.1.0
  bloc_test: ^9.1.5
  mocktail: ^1.0.2


flutter:
  uses-material-design: true

  assets:
    - assets/environment/


